package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitudDeTrabajo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Aprobado")
	private java.lang.Boolean aprobado;

	public SolicitudDeTrabajo() {
	}

	public java.lang.Boolean getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(java.lang.Boolean aprobado) {
		this.aprobado = aprobado;
	}

	public SolicitudDeTrabajo(java.lang.Boolean aprobado) {
		this.aprobado = aprobado;
	}

}