package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrabajoFinal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Estado")
	private java.lang.String estado;
	@org.kie.api.definition.type.Label(value = "Fecha de presentaci\u00F3n")
	private java.util.Date fecha;
	@org.kie.api.definition.type.Label(value = "T\u00EDtulo")
	private java.lang.String titulo;
	@org.kie.api.definition.type.Label(value = "Tutor")
	private java.lang.String tutor;

	public TrabajoFinal() {
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public java.util.Date getFecha() {
		return this.fecha;
	}

	public void setFecha(java.util.Date fecha) {
		this.fecha = fecha;
	}

	public java.lang.String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(java.lang.String titulo) {
		this.titulo = titulo;
	}

	public java.lang.String getTutor() {
		return this.tutor;
	}

	public void setTutor(java.lang.String tutor) {
		this.tutor = tutor;
	}

	public TrabajoFinal(java.lang.String estado, java.util.Date fecha,
			java.lang.String titulo, java.lang.String tutor) {
		this.estado = estado;
		this.fecha = fecha;
		this.titulo = titulo;
		this.tutor = tutor;
	}

}