package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Constantes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Correo UCA")
	@org.kie.api.definition.type.Description("Dirección de correo remitente de la UCA para el envío de los correos")
	private java.lang.String correoUCA;

	public Constantes() {
	}

	public java.lang.String getCorreoUCA() {
		return this.correoUCA;
	}

	public void setCorreoUCA(java.lang.String correoUCA) {
		this.correoUCA = correoUCA;
	}

	public Constantes(java.lang.String correoUCA) {
		this.correoUCA = correoUCA;
	}

}