package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Constantes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Correo UCA")
	@org.kie.api.definition.type.Description("Dirección de correo remitente de la UCA para el envío de los correos")
	private java.lang.String correoUCA;

	@org.kie.api.definition.type.Description(value = "Direcci\u00F3n de correo de la Secretar\u00EDa para el env\u00EDo de los correos")
	@org.kie.api.definition.type.Label(value = "Correo Secretar\u00EDa")
	private java.util.List<java.lang.String> correoSecretaria;

	public Constantes() {
	}

	public java.lang.String getCorreoUCA() {
		return this.correoUCA;
	}

	public void setCorreoUCA(java.lang.String correoUCA) {
		this.correoUCA = correoUCA;
	}

	public java.util.List<java.lang.String> getCorreoSecretaria() {
		return this.correoSecretaria;
	}
	
	public java.lang.String getCorreoSecretaria(String separador) {
		return String.join(separador, correoSecretaria);
	}

	public void setCorreoSecretaria(
			java.util.List<java.lang.String> correoSecretaria) {
		this.correoSecretaria = correoSecretaria;
	}

	public Constantes(java.lang.String correoUCA,
			java.util.List<java.lang.String> correoSecretaria) {
		this.correoUCA = correoUCA;
		this.correoSecretaria = correoSecretaria;
	}

}