package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitudDeTrabajo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SolicitudDeTrabajo() {
    }




}