package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrabajoFinal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Estado")
	private java.lang.String estado;
	@org.kie.api.definition.type.Label("Título")
	private java.lang.String titulo;
	@org.kie.api.definition.type.Label("Tutor")
	private Tutor tutor;
	@org.kie.api.definition.type.Label("Fecha de presentación")
	private java.util.Date fecha;

	public TrabajoFinal() {
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public java.lang.String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(java.lang.String titulo) {
		this.titulo = titulo;
	}

	public java.util.Date getFecha() {
		return this.fecha;
	}

	public void setFecha(java.util.Date fecha) {
		this.fecha = fecha;
	}

	public com.uca.Tutor getTutor() {
		return this.tutor;
	}

	public void setTutor(com.uca.Tutor tutor) {
		this.tutor = tutor;
	}

	public TrabajoFinal(java.lang.String estado, java.lang.String titulo,
			com.uca.Tutor tutor, java.util.Date fecha) {
		this.estado = estado;
		this.titulo = titulo;
		this.tutor = tutor;
		this.fecha = fecha;
	}

}