package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Tutor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Nombre y Apellido")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Direcci\u00F3n de correo electr\u00F3nico")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "Trabajo final asignado")
	private java.util.List<com.uca.TrabajoFinal> trabajoFinalAsignado;

	public Tutor() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.util.List<com.uca.TrabajoFinal> getTrabajoFinalAsignado() {
		return this.trabajoFinalAsignado;
	}

	public void setTrabajoFinalAsignado(
			java.util.List<com.uca.TrabajoFinal> trabajoFinalAsignado) {
		this.trabajoFinalAsignado = trabajoFinalAsignado;
	}

	public Tutor(java.lang.String nombre, java.lang.String email,
			java.util.List<com.uca.TrabajoFinal> trabajoFinalAsignado) {
		this.nombre = nombre;
		this.email = email;
		this.trabajoFinalAsignado = trabajoFinalAsignado;
	}

}