package com.uca;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Tutor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nombre y Apellido")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label("Dirección de correo electrónico")
	private java.lang.String email;
	public Tutor() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public Tutor(java.lang.String nombre, java.lang.String email) {
		this.nombre = nombre;
		this.email = email;
	}

}